PREFIX lamd: <http://publications.europa.eu/resources/authority/lam/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>

# testing lamd:class_REFANNOT LAM property classification

ASK
WHERE {
  VALUES ?subject {lamd:class_REFANNOT} .
  ?subject a skos:Collection .
  ?subject skos:definition ?defintion .
  ?subject skos:notation ?notation .
  ?subject skos:prefLabel ?prefLabel .
  ?subject euvoc:order ?order .
  lamd:class_REF skos:member ?subject .
}