PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lam: <http://publications.europa.eu/ontology/lam-skos-ap#>
PREFIX celexd: <http://publications.europa.eu/resources/authority/celex/>

# testing celexd:c_0 LAM CELEX classes
# TODO: should it also be inScheme with celexd:CelexLegalDocument?
# TODO: InverseTripleMaker function is using lowercase strings? check celexd:c_5_ag instead of c_5_AG and class_5_consil instead of class_5_CONSIL

ASK
WHERE {
  VALUES ?subject {celexd:c_5_AG_OJC}
  ?subject ?predicate ?object .
  ?subject a skos:Concept, lam:LegalDocumentClass .
  ?subject skos:inScheme lam:LegalDocumentClass .
#  ?subject skos:topConceptOf lam:LegalDocumentClass .
  ?subject skos:notation ?notation .
  ?subject skos:prefLabel ?prefLabel .
  ?subject skos:broader celexd:c_5_AG .
  celexd:class_5_CONSIL skos:member ?subject .
  ?subject lam:hasPropertyConfiguration ?prop_config .
  ?subject skos:editorialNote ?editorial_note .
  ?subject skos:example ?example .
}

