PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX lam: <http://publications.europa.eu/ontology/lam-skos-ap#>
PREFIX lamd: <http://publications.europa.eu/resources/authority/lam/>
PREFIX at: <http://publications.europa.eu/resource/authority/>

# testing ADDITION LAM properties

ASK
WHERE {
  VALUES ?subject {lamd:md_ADDITION}
  ?subject lam:hasAnnotationConfiguration  ?ac1 .
  ?ac1 sh:minCount "1"^^xsd:int .
  ?ac1 lam:path ?path1 .
  VALUES ?path1 { lamd:md_ANN_TLT lamd:md_ANN_SOV lamd:md_ANN_EOV } .
  FILTER NOT EXISTS { ?ac1 sh:class ?val } .

  ?subject lam:hasAnnotationConfiguration  ?ac2 .
  ?ac2 sh:minCount "1"^^xsd:int .
  ?ac2 lam:path lamd:md_ANN_RL2 .
  ?ac2 sh:class at:fd_375 .

  ?subject lam:hasAnnotationConfiguration  ?ac3 .
  ?ac3 sh:minCount "1"^^xsd:int .
  ?ac3 lam:path ?path2 .
  VALUES ?path2 { lamd:md_ANN_MDL lamd:md_ANN_MSL } .
  ?ac3 sh:class at:subdivision .

  ?subject lam:hasAnnotationConfiguration  ?ac4 .
  ?ac4 sh:minCount "1"^^xsd:int .
  ?ac4 lam:path lamd:md_ANN_LVL .
  ?ac4 sh:class at:language .
}