PREFIX lam: <http://publications.europa.eu/ontology/lam-skos-ap#>
PREFIX lamd: <http://publications.europa.eu/resources/authority/lam/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX fd_365: <http://publications.europa.eu/resource/authority/fd_365/>

# testing lamd:c_024 LAM class property configuration (lamd:md_DD)
# this test does not pass because hasAnnotationConfiguration relationship between the property configuration and
# the annotation configuration is missing.

ASK
WHERE {
  VALUES ?subject {lamd:c_024} .
  ?subject lam:hasPropertyConfiguration ?pc .
  ?pc lam:path lamd:md_DD .
  ?pc sh:minCount 1 .
  ?pc sh:maxCount 1 .
  ?pc lam:hasAnnotationConfiguration ?ac .
  ?ac lam:path lamd:md_ANN_COD .
  ?ac sh:minCount 1 .
  ?ac sh:hasValue fd_365:DATADOPT .

}