PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX lam: <http://publications.europa.eu/ontology/lam-skos-ap#>
PREFIX lamd: <http://publications.europa.eu/resources/authority/lam/>
PREFIX at: <http://publications.europa.eu/resource/authority/>

# testing Date of effect LAM properties
# TODO: should we use sh:hasValue or sh:class for line 20?
# TODO: minCount is not working properly?

ASK
WHERE {
  VALUES ?subject {lamd:md_IF}
  ?subject lam:hasAnnotationConfiguration  ?ac  .
#  ?ac sh:minCount 1 .
  ?ac sh:path ?path .
  VALUES ?path { lamd:md_ANN_TOD lamd:md_ANN_COD } .
  ?ac sh:hasValue at:fd_335 .
}