PREFIX lam: <http://publications.europa.eu/ontology/lam-skos-ap#>
PREFIX lamd: <http://publications.europa.eu/resources/authority/lam/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# testing lamd:c_022 LAM class property configuration (lamd:md_MI)
# changed lam:path to sh:path
# TODO: minCount is not working properly?

ASK
WHERE {
  VALUES ?subject {lamd:c_022} .
  ?subject lam:classifyWith  ?cw  .
  ?cw sh:path ?lam_path .
  #?cw sh:minCount 1 .
  ?cw sh:hasValue ?val .
}